### ISSUE TITLE
CORS is broken in 1.0.2

### ISSUE THREAD

**Issue by molekilla** [vechain/thor#145]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Centos Linux / Docker

## Expected behavior
Migrating to Thor Docker v1.0.2 should not break CORS

## Actual behavior
Chrome returns
```
Failed to load https://test.local/events?address=0x7ca903d8f7a9ae6c79c6825c1382157b7df5e003&order=ASC: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3100, *', but only one is allowed. Origin 'http://localhost:3100' is therefore not allowed access.
```

## Steps to reproduce the behavior
Run Docker with
```
---
    name: thor-test
    image: vechain/thor:v1.0.2
    command: --verbosity 5 --network test --api-addr=0.0.0.0:8669 --api-cors "http://localhost:3100"
    state: started
    ports:
    - "0.0.0.0:8669:8669"
    - "11235:11235/udp"
    - "11235:11235"
    volumes:
    - /opt/vechain/test/.org.vechain.thor:/root/.org.vechain.thor
```
